# Generated by Django 4.1.4 on 2022-12-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('usedCoupons', models.TextField(default='[]')),
                ('acountType', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.TextField(verbose_name='')),
                ('phone', models.TextField()),
                ('website', models.TextField()),
                ('adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='')),
                ('expire', models.TextField(default='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktivana.account')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expireTime', models.IntegerField(default=0)),
                ('useTime', models.IntegerField(default=1)),
                ('picture', models.TextField()),
                ('code', models.TextField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktivana.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('password', models.TextField(default='')),
                ('signupCode', models.TextField(default='')),
                ('activeCoupons', models.ManyToManyField(to='aktivana.coupon')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aktivana.company'),
        ),
        migrations.AddField(
            model_name='account',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aktivana.partner'),
        ),
    ]
