# Generated by Django 4.1 on 2022-11-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('website', models.TextField()),
                ('adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expireTime', models.IntegerField(default=0)),
                ('useTime', models.IntegerField(default=1)),
                ('picture', models.TextField()),
                ('code', models.TextField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktivana.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('signupCode', models.TextField(default='bhcwdcrpc')),
                ('activeCoupons', models.ManyToManyField(to='aktivana.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('usedCoupons', models.TextField(default='[]')),
                ('acountType', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktivana.company')),
            ],
        ),
    ]
