# Generated by Django 4.1 on 2022-11-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiretime', models.IntegerField(default=0)),
                ('useTime', models.IntegerField(default=1)),
                ('picture', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('signupCode', models.TextField(default=',,,pnbco,')),
                ('activeCodes', models.ManyToManyField(to='aktivana.code')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('website', models.TextField()),
                ('adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('usedCodes', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktivana.company')),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktivana.partner'),
        ),
    ]
