# Generated by Django 4.1 on 2022-11-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivana', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='expiretime',
            new_name='expireTime',
        ),
        migrations.AlterField(
            model_name='company',
            name='signupCode',
            field=models.TextField(default='bgckvrlhc'),
        ),
    ]
