# Generated by Django 4.1 on 2022-11-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aktivana', '0002_rename_expiretime_code_expiretime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expireTime', models.IntegerField(default=0)),
                ('useTime', models.IntegerField(default=1)),
                ('picture', models.TextField()),
                ('code', models.TextField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktivana.partner')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='activeCodes',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='usedCodes',
        ),
        migrations.AddField(
            model_name='employee',
            name='usedCoupons',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='company',
            name='signupCode',
            field=models.TextField(default='erdrtshol'),
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.AddField(
            model_name='company',
            name='activeCoupons',
            field=models.ManyToManyField(to='aktivana.coupon'),
        ),
    ]
