# Generated by Django 4.0.5 on 2022-11-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivana', '0003_coupon_remove_company_activecodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='signupCode',
            field=models.TextField(default='rchqafbcl'),
        ),
    ]
