# Generated by Django 4.0.5 on 2022-11-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivana', '0007_alter_company_signupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='signupCode',
            field=models.TextField(default='cdevlthsy'),
        ),
    ]
