# Generated by Django 4.1 on 2022-11-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivana', '0009_alter_company_signupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='signupCode',
            field=models.TextField(default='djtaejkxa'),
        ),
    ]
