# Generated by Django 4.0.5 on 2022-11-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktivana', '0010_rename_acount_account_alter_company_signupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='signupCode',
            field=models.TextField(default='ltqhcdkyf'),
        ),
    ]
