# Generated by Django 4.0.5 on 2022-11-07 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aktivana', '0011_alter_company_signupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='signupCode',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='')),
                ('expire', models.TextField(default='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktivana.account')),
            ],
        ),
    ]
