# Generated by Django 4.0.5 on 2022-12-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktivana', '0014_account_partner_alter_account_company'),
        ('aktivana', '0014_remove_partner_email_remove_partner_name_and_more'),
    ]

    operations = [
    ]
